### ISSUE TITLE
Add Acquia settings include

### ISSUE THREAD

**Issue by grasmash** [acquia/drupal-recommended-project#67] opened 2022-01-06 19:00 UTC
Customers who do not use BLT must manually add a settings include line to their acquia/drupal-recommended-project application. I'd like to remove this requirement by adding the following to settings.php by default:

```
if (file_exists('/var/www/site-php')) {
  require "/var/www/site-php/{$_ENV['AH_SITE_GROUP']}/{$_ENV['AH_SITE_GROUP']}-settings.inc";
}
```

This could be accomplished in a few ways.

**Comment by danepowell** [comment] 2022-01-07 16:16
You can [dynamically append to scaffolded files](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_4) like default.settings.php. This seems like the best solution. Then settings.php (copied from default.settings.php) should have the include line whenever it gets created.

One other option... I've been considering expanding this project template into a full-fledged Drupal application, including settings and config, basically more like a distribution. Essentially eliminating the need for a separate Canary application. In which case we could just commit settings.php, although we'd need to keep it up to date with Drupal core somehow.

**Comment by danepowell** [comment] 2022-01-13 16:54
Actually Acquia CMS already tries to do exactly what I described, appending the Acquia settings require line to default.settings.php: https://github.com/acquia/acquia_cms/blob/837c1619ea35c29cfbceb2d9c9b994abce789b19/composer.json#L119

The problem is that it doesn't seem to apply ordinarily, _but_ as soon as _I_ try to append my own file in the project template composer.json it somehow triggers Acquia CMS to apply its own as well. We need to disentangle these.

**Comment by danepowell** [comment] 2022-01-14 18:16
Acquia CMS shouldn't be mucking about with scaffold files (default.settings.php), that's a project template's purview. @grasmash you might want to coordinate with the ACMS team on this in my absence.

**Comment by mglaman** [comment] 2022-01-20 16:41
There's a big conflict here. This project puts config in `../config/default` and ACMS says `../config` https://github.com/acquia/acquia_cms/blob/837c1619ea35c29cfbceb2d9c9b994abce789b19/patches/d9-acms-settings.patch#L51

**Comment by vishalkhode1** [comment] 2024-03-29 16:09
Closing, as the project now includes the acquia/drupal-recommended-settings plugin.

**Closed by vishalkhode1** 2024-03-29 16:09 UTC
Labels: enhancement
