### ISSUE TITLE
DX-5157: Running acms:install fails because database has not been configured

### ISSUE THREAD

**Issue by mglaman** [acquia/drupal-recommended-project#217] opened 2022-08-24 15:17 UTC
I ran the following:

```
php vendor/bin/acms acms:install acquia_cms_enterprise_low_code --no-interaction
```

The process crashed because no database settings have been configured.

```
Installing Site:
----------------
> './vendor/bin/drush' 'site:install' 'minimal' '--site-name=Acquia CMS Enterprise Low-code' '--yes'
 [warning] Program mysql not found. Proceed if you have already created or emptied the Drupal database.

 You are about to:
 * Create a sites/default/settings.php file

 // Do you want to continue?: yes.

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements

In install.core.inc line 971:

  Resolve all issues below to continue the installation. For help configuring your database server, see the <a href="https://www.drupal.org/docs/8/install">installation handbook</a>, or contact your hosting provider.<div class
  ="item-list"><ul><li>Failed to connect to your database server. The server reports the following message: <em class="placeholder">SQLSTATE[HY000] [2002] Connection refused</em>.<ul><li>Is the database server running?</li><li
  >Does the database exist or does the database user have sufficient privileges to create the database?</li><li>Have you entered the correct database name?</li><li>Have you entered the correct username and password?</li><li>Ha
  ve you entered the correct database hostname and port number?</li></ul></li></ul></div>
```

**Comment by danepowell** [comment] 2022-08-25 14:55
This seems like a dupe of #67 . Anyway, the project template can't know what your db settings are, the best it could do is append a server-side include which is the scope of #67.

**Closed by danepowell** 2022-08-25 14:55 UTC

**Comment by mglaman** [comment] 2022-08-25 15:39
I suppose. I was thinking the scaffolding (`composer require`) should be separate from the installation (`drush si; drush en`) but I guess that cannot be done due to needing to specify what modules must be installed.
